apiVersion: v1
kind: ReplicationController
metadata:
  name: es-data-1
spec:
  replicas: 1
  selector:
    component: elasticsearch
    role: data
    id: es-data-1
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
        id: es-data-1 
    spec:
      containers:
      - name: es-data-1
        securityContext:
          privileged: true 
          capabilities:
            add:
              - IPC_LOCK
        image: 172.22.111.199:80/cloud/elasticsearch:1.1_1003
        imagePullPolicy: Always
        resources:
          limits:
            memory: "12288Mi"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          value: "es-sg"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_DATA
          value: "true"
        - name: NODE_INGEST
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: NETWORK_HOST 
          value: "0.0.0.0"
        - name: DISCOVERY_SERVICE
          value: "elasticsearch-discovery"
        - name: NAMESPACE
          value: "default"
        - name: MINIMUM_MASTER_NODES
          value: "2" 
        - name: ES_JAVA_OPTS
          value: "-Xms10g -Xmx10g"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data 
          name: data
        - mountPath: /backups
          name: backup
      volumes:
        - name: data
          hostPath:
            path: /data/es-data
        - name: backup
          hostPath:  
            path: /data/es-backup
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: es-data-2
spec:
  replicas: 1
  selector:
    component: elasticsearch
    role: data
    id: es-data-2
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
        id: es-data-2
    spec:
      containers:
      - name: es-data-2
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: 172.22.111.199:80/cloud/elasticsearch:1.1_1003
        imagePullPolicy: Always
        resources:
          limits:
            memory: "12288Mi"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          value: "es-sg"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_DATA
          value: "true"
        - name: NODE_INGEST
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: NETWORK_HOST 
          value: "0.0.0.0"
        - name: DISCOVERY_SERVICE
          value: "elasticsearch-discovery"
        - name: NAMESPACE
          value: "default"
        - name: MINIMUM_MASTER_NODES
          value: "2" 
        - name: ES_JAVA_OPTS
          value: "-Xms10g -Xmx10g"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data 
          name: data
        - mountPath: /backups
          name: backup
      volumes:
        - name: data
          hostPath:
            path: /data/es-data
        - name: backup
          hostPath:
            path: /data/es-backup
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: es-data-3
spec:
  replicas: 1
  selector:
    component: elasticsearch
    role: data
    id: es-data-3
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
        id: es-data-3
    spec:
      containers:
      - name: es-data-3
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: 172.22.111.199:80/cloud/elasticsearch:1.1_1003
        imagePullPolicy: Always
        resources:
          limits:
            memory: "12288Mi"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          value: "es-sg"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_DATA
          value: "true"
        - name: NODE_INGEST
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: NETWORK_HOST 
          value: "0.0.0.0"
        - name: DISCOVERY_SERVICE
          value: "elasticsearch-discovery"
        - name: NAMESPACE
          value: "default"
        - name: MINIMUM_MASTER_NODES
          value: "2" 
        - name: ES_JAVA_OPTS
          value: "-Xms10g -Xmx10g"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data 
          name: data
        - mountPath: /backups
          name: backup
      volumes:
        - name: data
          hostPath:
            path: /data/es-data
        - name: backup
          hostPath:
            path: /data/es-backup
