apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  labels:
    component: elasticsearch
spec:
  selector:
    component: elasticsearch
  clusterIP: "None"
  ports:
  - name: transport
    port: 9300
    targetPort: 9300
    protocol: TCP
  - name: http
    port: 9200
    targetPort: 9200
    protocol: TCP
