apiVersion: v1
kind: ReplicationController
metadata:
  name: es-master-1
spec:
  replicas: 1
  selector:
    component: elasticsearch
    role: master
    id: es-master-1
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
        id: es-master-1
    spec:
      containers:
      - name: es-master-1
        securityContext:
          privileged: true 
          capabilities:
            add:
              - IPC_LOCK
        image: 172.22.111.199:80/cloud/elasticsearch:1.1_1003
        imagePullPolicy: Always
        resources:
          limits:
            memory: "4096Mi"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          value: "es-sg"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "false"
        - name: NODE_INGEST
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: NETWORK_HOST
          value: "0.0.0.0"
        - name: DISCOVERY_SERVICE
          value: "elasticsearch-discovery"
        - name: NAMESPACE
          value: "default"
        - name: MINIMUM_MASTER_NODES
          value: "2" 
        - name: ES_JAVA_OPTS
          value: "-Xms2g -Xmx2g"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: es-master-2
spec:
  replicas: 1
  selector:
    component: elasticsearch
    role: master
    id: es-master-2
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
        id: es-master-2
    spec:
      containers:
      - name: es-master-2
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: 172.22.111.199:80/cloud/elasticsearch:1.1_1003
        imagePullPolicy: Always
        resources:
          limits:
            memory: "4096Mi"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          value: "es-sg"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "false"
        - name: NODE_INGEST
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: NETWORK_HOST
          value: "0.0.0.0"
        - name: DISCOVERY_SERVICE
          value: "elasticsearch-discovery"
        - name: NAMESPACE
          value: "default"
        - name: MINIMUM_MASTER_NODES
          value: "2"
        - name: ES_JAVA_OPTS
          value: "-Xms2g -Xmx2g"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: es-master-3
spec:
  replicas: 1
  selector:
    component: elasticsearch
    role: master
    id: es-master-3
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
        id: es-master-3
    spec:
      containers:
      - name: es-master-3
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: 172.22.111.199:80/cloud/elasticsearch:1.1_1003
        imagePullPolicy: Always
        resources:
          limits:
            memory: "4096Mi"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          value: "es-sg"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "false"
        - name: NODE_INGEST
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: NETWORK_HOST
          value: "0.0.0.0"
        - name: DISCOVERY_SERVICE
          value: "elasticsearch-discovery"
        - name: NAMESPACE
          value: "default"
        - name: MINIMUM_MASTER_NODES
          value: "2" 
        - name: ES_JAVA_OPTS
          value: "-Xms2g -Xmx2g"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
