cluster:
  name: ${CLUSTER_NAME}

node:
  name: ${HOSTNAME}
  master: ${NODE_MASTER}
  data: ${NODE_DATA}
  ingest: ${NODE_INGEST}

node.max_local_storage_nodes: 1

network.host: ${NETWORK_HOST}


http:
  enabled: ${HTTP_ENABLE}
  compression: true
  cors:
    enabled: true
    allow-origin: "*"

cloud:
  kubernetes:
    service: ${DISCOVERY_SERVICE}
    namespace: ${NAMESPACE}

discovery:
    type: kubernetes
    zen.hosts_provider: kubernetes
    zen.fd.ping_interval: 5s
    zen.fd.ping_timeout: 10s
    zen.fd.ping_retries: 3
    zen.minimum_master_nodes: ${MINIMUM_MASTER_NODES}
    zen.master_election.ignore_non_master_pings: true

bootstrap:
    memory_lock: true

path.repo: ["/backups"]

## Indices settings
#indices:
#    memory:
#        index_buffer_size: 30%
#        min_index_buffer_size: 96mb

# restart settings
gateway.recover_after_time: 5m
gateway.recover_after_data_nodes: 2
#gateway.recover_after_master_nodes: 3

cluster.routing.allocation.same_shard.host: true

indices.fielddata.cache.size: 50%
