apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat 
  labels:
    component: elk
    role: filebeat
spec:
  template:
    metadata:
      labels:
        component: elk
        role: filebeat 
    spec:
      containers:
      - name: filebeat
        image: 172.22.111.199:80/cloud/filebeat:1.1_1003
        resources:
          limits:
            memory: 100Mi
            cpu: 100m
#          requests:
#            cpu: 200m
#            memory: 200Mi
        env:
          - name: KAFKA_HOSTS
            value: "'kafka:9092'"
          - name: LOG_LEVEL
            value: warning
        volumeMounts:
        - name: varlog
          mountPath: /var/log/containers
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config
          mountPath: /etc/filebeat 
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/containers
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config
        configMap:
          name: filebeat-log
