apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana
  labels:
    component: elk
    role: kibana
spec:
  replicas: 1
  selector:
    component: elk
    role: kibana
  template:
    metadata:
      labels:
        component: elk
        role: kibana
    spec:
      containers:
      - name: kibana
        image: 172.22.111.199:80/cloud/kibana:1.1_1003
        env:
        - name: ELASTICSEARCH_URL 
          value: "http://elasticsearch:9200"
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
