apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    component: elk
    role: kibana
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    component: elk
    role: kibana
  ports:
  - name: http
    nodePort: 30001
    port: 5601
    protocol: TCP
